# Generated by Django 5.2.6 on 2025-09-05 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_touch', '0002_alter_ubicacion_departamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ubicacion',
            name='departamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ubicaciones', to='app_touch.departamento'),
        ),
    ]
