# Generated by Django 5.2.6 on 2025-09-09 11:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_touch', '0003_alter_ubicacion_departamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trabajador',
            name='departamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trabajadores', to='app_touch.departamento'),
        ),
    ]
