# Generated by Django 5.2.6 on 2025-09-12 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_touch', '0004_alter_trabajador_departamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='ubicacion',
            name='categoria',
            field=models.CharField(choices=[('porteria', 'Portería'), ('departamento', 'Departamento'), ('gerencia', 'Gerencia/Subgerencia'), ('servicio', 'Baño/Camarín'), ('jefatura', 'Jefatura'), ('bodega', 'Bodega'), ('via', 'Calle/Pasillo')], default='departamento', max_length=50),
        ),
    ]
