# Generated by Django 5.2.6 on 2025-09-12 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_touch', '0005_ubicacion_categoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mapa',
            name='zonas_seguras',
        ),
        migrations.AddField(
            model_name='ubicacion',
            name='tipo_emergencia',
            field=models.CharField(blank=True, choices=[('incendio', 'Incendio'), ('sismo', 'Sismo')], help_text="Solo aplica si la categoría es 'segura'", max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ubicacion',
            name='categoria',
            field=models.CharField(choices=[('porteria', 'Portería'), ('departamento', 'Departamento'), ('gerencia', 'Gerencia/Subgerencia'), ('servicio', 'Baño/Camarín'), ('jefatura', 'Jefatura'), ('bodega', 'Bodega'), ('via', 'Calle/Pasillo'), ('estacionamiento', 'Estacionamiento'), ('fumadores', 'Zona de Fumadores'), ('segura', 'Ubicación Segura')], default='departamento', max_length=50),
        ),
        migrations.DeleteModel(
            name='ZonaSegura',
        ),
    ]
