# Generated by Django 5.2.6 on 2025-09-22 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_touch', '0006_remove_mapa_zonas_seguras_ubicacion_tipo_emergencia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trabajador',
            name='last_logon',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
