# Generated by Django 5.2.6 on 2025-09-23 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_touch', '0007_trabajador_last_logon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trabajador',
            old_name='last_logon',
            new_name='ultima_conexion',
        ),
        migrations.AddField(
            model_name='trabajador',
            name='compañia',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='trabajador',
            name='cuenta_activa',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='trabajador',
            name='grupo_info',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='trabajador',
            name='jefatura_directa',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='trabajador',
            name='miembro_info',
            field=models.TextField(blank=True, null=True),
        ),
    ]
