# Generated by Django 5.2.6 on 2025-09-23 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_touch', '0008_rename_last_logon_trabajador_ultima_conexion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trabajador',
            name='supervisa_a',
            field=models.ManyToManyField(blank=True, related_name='supervisado_por', to='app_touch.trabajador'),
        ),
    ]
