# Generated by Django 5.2.6 on 2025-09-23 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_touch', '0009_trabajador_supervisa_a'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trabajador',
            name='grupo_info',
        ),
        migrations.RemoveField(
            model_name='trabajador',
            name='miembro_info',
        ),
    ]
