# Generated by Django 5.2.6 on 2025-09-25 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_touch', '0010_remove_trabajador_grupo_info_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trabajador',
            name='nivel_jefatura',
            field=models.CharField(blank=True, choices=[('gerente', 'Gerente'), ('subgerente', 'Subgerente'), ('jefe', 'Jefe'), ('ninguno', 'Ninguno')], default='ninguno', max_length=20),
        ),
    ]
