# Generated by Django 5.2.6 on 2025-09-25 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_touch', '0011_trabajador_nivel_jefatura'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trabajador',
            name='nivel_jefatura',
        ),
    ]
