# Generated by Django 5.2.6 on 2025-10-14 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_touch', '0012_remove_trabajador_nivel_jefatura'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ubicacion',
            name='categoria',
            field=models.CharField(choices=[('porteria', 'Portería'), ('departamento', 'Departamento'), ('gerencia', 'Gerencia/Subgerencia'), ('servicio', 'Baño/Camarín'), ('jefatura', 'Jefatura'), ('bodega', 'Bodega'), ('via', 'Calle/Pasillo'), ('estacionamiento', 'Estacionamiento'), ('fumadores', 'Zona de Fumadores'), ('segura', 'Ubicación Segura'), ('inicio', 'Punto de Inicio'), ('casino', 'Casino'), ('cancha', 'Cancha/Área Deportiva')], default='departamento', max_length=50),
        ),
    ]
