# Generated by Django 5.2.6 on 2026-02-26 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_touch', '0013_alter_ubicacion_categoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='QRToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('used', models.BooleanField(db_index=True, default=False)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('device_info', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['token', 'used'], name='app_touch_q_token_b71cb5_idx'), models.Index(fields=['expires_at', 'used'], name='app_touch_q_expires_865ea9_idx')],
            },
        ),
    ]
