# Generated by Django 5.2.6 on 2026-03-04 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_touch', '0014_qrtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrtoken',
            name='device_fingerprint',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
